# Generated by Django 3.1.7 on 2021-03-28 19:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tar_included', models.BooleanField()),
                ('subscription', models.FloatField()),
                ('cycle', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly')], max_length=25)),
                ('type_time', models.CharField(choices=[('bi-time', 'bi-time'), ('tri-time', 'tri-time'), ('simple', 'simple')], max_length=25)),
                ('offer_iva', models.BooleanField()),
                ('off_peak_price', models.FloatField()),
                ('peak_price', models.FloatField()),
                ('unit', models.CharField(choices=[('kwh', 'kwh'), ('min', 'min')], max_length=25)),
                ('valid', models.BooleanField()),
                ('publish', models.BooleanField()),
                ('vat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
